# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: /
    weight: 10
    identifier: aboutme_parent

 # NEW ITEM: This will be the first item in your About Me dropdown
  - name: Homepage # Or "About Me Overview", "Bio", etc.
    url: /         # This links to your main About Me (homepage)
    weight: 11     # Make it appear first in the dropdown
    parent: aboutme_parent # Link to the 'About Me' parent

  - name: Athletics
    url: athletics/
    weight: 12
    parent: aboutme_parent

  - name: CV
    url: cv/
    weight: 20

  - name: Research
    url: research/
    weight: 30
    # Add an identifier for the parent item
    identifier: research_parent # This needs to be a unique identifier.

   # NEW ITEM: This will be the first item in your Research dropdown
  - name: Research Overview # You can name this "Research Overview", "View All Research", etc.
    url: research/    # This is the crucial part: it links to your main research page
    weight: 31        # Make sure its weight is lower than Publications to appear first
    parent: research_parent

  - name: Publications
    url: publication/
    weight: 32
    # Set the parent to the identifier of the Research item
    parent: research_parent # This links it to the 'Research' item
  
 


  #- name: "Publications"
    #url: "/publication"
    #weight: 40
  #- name: Teaching
    #url: teaching/
    #weight: 50
  #- name: Athletics
    #url: athletics/
    #weight: 60

    
