# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main: 
  - name: About Me
    url: /
    weight: 1
  #- name: Papers
    #url: /#papers
    #weight: 2
  - name: CV
    url: cv/
    weight: 3
  #- name: Research
    #url: projects/
    #weight: 4
  #- name: Teaching
    #url: teaching/
    #weight: 5
  #- name: Athletics
    #url: athletics/
    #weight: 6

    
