# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: /
    weight: 10

  - name: CV
    url: cv/
    weight: 20

  - name: Research
    url: research/
    weight: 30
    # Add an identifier for the parent item
    identifier: research_parent # This needs to be a unique identifier.

  - name: Publications
    url: publication/
    weight: 40
    # Set the parent to the identifier of the Research item
    parent: research_parent # This links it to the 'Research' item
  
  - name: Athletics
    url: athletics/
    weight: 50


  #- name: "Publications"
    #url: "/publication"
    #weight: 40
  #- name: Teaching
    #url: teaching/
    #weight: 50
  #- name: Athletics
    #url: athletics/
    #weight: 60

    
