# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: teal

font:
  font_size: xs

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Julianna J. Thomson Personal Website'
  analytics:
    google_analytics: 'G-7M08GWK835'
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Julianna J. Thomson"

# Site footer
#footer:
  #copyright:
    #notice: '© {2025}.'
    #license:
      #enable: true
      #allow_derivatives: false
      #share_alike: true
      #allow_commercial: false

# Localization
locale:
  date_format: '2006'
  

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

customCSS: [css/custom.css]
